In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
print("test")

test

In [3]:
pd.read_csv("dataset/user_profiles.csv")

,id,user_id,age,gender,height_cm,fitness_level,primary_goal,available_equipment,days_per_week,time_per_session,medical_notes
0,1,1,41,female,161.16,intermediate,muscle_gain,['dumbbells'],3,60,NaN
1,2,2,64,female,168.08,intermediate,weight_loss,"['punching_bag', 'bodyweight', 'kettlebell']",4,30,NaN
2,3,3,41,male,178.18,intermediate,muscle_gain,"['kettlebell', 'punching_bag', 'dumbbells']",4,60,NaN
3,4,4,56,male,189.64,beginner,skill_boxing,['punching_bag'],4,60,NaN
4,5,5,65,male,174.86,beginner,weight_loss,['kettlebell'],5,30,Minor knee pain
...,...,...,...,...,...,...,...,...,...,...,...
995,996,996,62,male,164.81,beginner,muscle_gain,"['bodyweight', 'resistance_bands', 'kettlebell']",3,30,NaN
996,997,997,58,male,168.89,beginner,general_fitness,['punching_bag'],5,45,NaN
997,998,998,41,male,186.12,intermediate,muscle_gain,['bodyweight'],5,45,NaN
998,999,999,46,male,169.19,intermediate,skill_boxing,['kettlebell'],3,30,NaN
999,1000,1000,50,male,189.23,beginner,weight_loss,['kettlebell'],5,30,Minor knee pain