In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
print("test")

test

In [3]:
pd.read_csv("dataset/user_profiles.csv")

,id,user_id,age,gender,height_cm,fitness_level,primary_goal,available_equipment,days_per_week,time_per_session,medical_notes
0,1,1,41,female,161.16,intermediate,muscle_gain,['dumbbells'],3,60,NaN
1,2,2,64,female,168.08,intermediate,weight_loss,"['punching_bag', 'bodyweight', 'kettlebell']",4,30,NaN
2,3,3,41,male,178.18,intermediate,muscle_gain,"['kettlebell', 'punching_bag', 'dumbbells']",4,60,NaN
3,4,4,56,male,189.64,beginner,skill_boxing,['punching_bag'],4,60,NaN
4,5,5,65,male,174.86,beginner,weight_loss,['kettlebell'],5,30,Minor knee pain
...,...,...,...,...,...,...,...,...,...,...,...
995,996,996,62,male,164.81,beginner,muscle_gain,"['bodyweight', 'resistance_bands', 'kettlebell']",3,30,NaN
996,997,997,58,male,168.89,beginner,general_fitness,['punching_bag'],5,45,NaN
997,998,998,41,male,186.12,intermediate,muscle_gain,['bodyweight'],5,45,NaN
998,999,999,46,male,169.19,intermediate,skill_boxing,['kettlebell'],3,30,NaN
999,1000,1000,50,male,189.23,beginner,weight_loss,['kettlebell'],5,30,Minor knee pain

In [5]:
pd.read_csv(r"C:\Users\zaid\Documents\mega_project\mmacraftai\module_01\dataset\user_progress.csv")

,id,user_id,log_date,weight_kg,body_fat_percentage,measurements
0,1,1,2025-04-17,99.1,25.1,"{""waist_cm"": 81, ""chest_cm"": 113}"
1,2,1,2025-04-28,99.6,23.1,"{""waist_cm"": 76, ""chest_cm"": 114}"
2,3,1,2025-04-29,98.1,32.9,"{""waist_cm"": 90, ""chest_cm"": 117}"
3,4,1,2025-05-10,98.9,30.1,"{""waist_cm"": 89, ""chest_cm"": 106}"
4,5,1,2025-05-19,96.6,15.9,"{""waist_cm"": 71, ""chest_cm"": 90}"
...,...,...,...,...,...,...
10135,10136,1000,2025-06-26,86.0,25.8,"{""waist_cm"": 93, ""chest_cm"": 107}"
10136,10137,1000,2025-07-01,85.8,16.7,"{""waist_cm"": 97, ""chest_cm"": 119}"
10137,10138,1000,2025-07-12,87.0,11.6,"{""waist_cm"": 71, ""chest_cm"": 105}"
10138,10139,1000,2025-07-16,86.2,33.3,"{""waist_cm"": 74, ""chest_cm"": 118}"
10139,10140,1000,2025-07-24,85.5,21.9,"{""waist_cm"": 75, ""chest_cm"": 94}"

In [8]:
pd.read_csv(r"dataset/users.csv")

,id,full_name,email,password_hash,phone_number,preferred_language,subscription_status,subscription_expiry,created_at,updated_at
0,1,Maanav Raghavan,mishrachaaya@example.com,49fffd93e57ff3bdb4e6fc2ddabec81370c463c3731d8a...,8368077115,mr,free,2025-08-28,2025-06-27 11:07:55,2025-07-03 09:54:40
1,2,Tara Parikh,ayaan41@example.com,e899f9569b1cba8a6f05bd209e5fe64ac5d0f48adefbf2...,917866342724,en,premium,2026-03-17,2024-11-21 09:11:48,2025-07-17 16:10:55
2,3,Isha Chahal,oeshikota@example.com,0798661fb752fe4a4474e98f196719ba9a265d4f44d881...,8900089706,en,free,2026-02-14,2025-01-13 08:50:57,2025-07-15 10:44:23
3,4,Yadavi Mittal,frado41@example.com,daeeb4fdb696192d2980f78cd57c44e338a546ad5c76ec...,5658666273,en,free,2025-07-22,2025-04-15 03:49:07,2025-07-07 02:15:59
4,5,Kabir Deep,nidhisagar@example.com,a94cec4ee53012d4630c094ccc22c34e6d0e23ac2c0463...,5148997960,mr,premium,2026-03-13,2024-05-26 23:28:04,2025-07-02 22:49:03
...,...,...,...,...,...,...,...,...,...,...
995,996,Lopa Uppal,gwarrior@example.net,4199615a91b19a24c0fda79d35ac6f63919074a8f964fe...,9171804418,mr,free,2026-06-10,2024-07-04 01:38:41,2025-07-11 06:52:30
996,997,Vidhi Mangat,barkha89@example.net,a1ae8c6a54d2ef031b326d2ee53850b2db3b099edb48af...,912870984556,hi,free,2025-11-17,2024-07-22 23:49:34,2025-07-18 14:00:48
997,998,Tara Varma,jyoti63@example.net,ef73c7989c7fefeb546b01ecc83d2b1df0133ca34bde56...,7136546796,hi,expired,2025-08-02,2025-06-24 04:42:12,2025-07-13 11:31:32
998,999,Kashvi Kale,bawasaumya@example.com,555acaab53ec7921270fd1fb5eaf24c7e4d8e08ac0d335...,916198842149,mr,expired,2025-10-18,2025-04-21 13:56:07,2025-07-10 01:46:16
999,1000,Daksh Dani,deyagnesh@example.org,0c294ac958feaeb4359ba985d3f64081044ef3433063dd...,919345476269,mr,expired,2026-06-13,2024-05-21 17:40:06,2025-07-25 21:34:40

In [10]:
pd.read_csv(r"C:\Users\zaid\Documents\mega_project\mmacraftai\module_01\dataset\exercises.csv")

,id,exercise_name,muscle_group,exercise_type,equipment_needed,video_url,instructions,difficulty_level
0,1,Monitored Zero Tolerance Graphical User Interface,Legs,strength,bodyweight,https://fightfit.ai/videos/ex_1.mp4,Veniam voluptatibus sapiente voluptate molliti...,beginner
1,2,Ameliorated Multimedia Internet Solution,Back,plyometric,dumbbells,https://fightfit.ai/videos/ex_2.mp4,Quaerat quidem molestias cupiditate quod ut. A...,advanced
2,3,Sharable Context-Sensitive Firmware,Biceps,strength,resistance_bands,https://fightfit.ai/videos/ex_3.mp4,Asperiores neque velit quisquam.,advanced
3,4,Configurable Even-Keeled Task-Force,Shoulders,plyometric,bodyweight,https://fightfit.ai/videos/ex_4.mp4,Laboriosam voluptate veritatis sint voluptas a...,intermediate
4,5,Expanded Analyzing Focus Group,Back,plyometric,resistance_bands,https://fightfit.ai/videos/ex_5.mp4,Aliquid totam harum assumenda mollitia. Quidem...,beginner
...,...,...,...,...,...,...,...,...
145,146,Digitized Full-Range Archive,Biceps,cardio,kettlebell,https://fightfit.ai/videos/ex_146.mp4,Ipsum sed ullam quod tempore. Delectus quidem ...,beginner
146,147,Ameliorated Needs-Based Archive,Biceps,stretch,bodyweight,https://fightfit.ai/videos/ex_147.mp4,Dolores labore harum quod ratione. Aliquid rem...,advanced
147,148,Streamlined Dynamic Open Architecture,Legs,plyometric,dumbbells,https://fightfit.ai/videos/ex_148.mp4,Amet esse maxime nostrum fugit autem. A quis a...,intermediate
148,149,Enhanced Non-Volatile Access,Triceps,strength,kettlebell,https://fightfit.ai/videos/ex_149.mp4,Ipsum sit numquam deleniti molestias non vero....,intermediate
149,150,Reduced Directional Budgetary Management,Back,plyometric,kettlebell,https://fightfit.ai/videos/ex_150.mp4,Aliquid exercitationem tenetur quasi quisquam ...,intermediate